- packages/core/src/lib/data-query/builder/dataQueryBuilder.ts
- packages/core/src/lib/data-query/executor.ts
- packages/core/src/lib/data-source/pg.ts
- packages/core/src/lib/template-engine/built-in-extensions/query-builder/reqTagRunner.ts
- packages/core/src/lib/template-engine/templateEngine.ts
- packages/core/src/models/extensions/dataSource.ts
- packages/core/test/data-query/builder/group-by-clause.spec.ts
- packages/core/test/data-query/builder/having-clause.spec.ts
- packages/core/test/data-query/builder/join-clause.spec.ts
- packages/core/test/data-query/builder/limit-offset-clause.spec.ts
- packages/core/test/data-query/builder/order-by-clause.spec.ts
- packages/core/test/data-query/builder/select-clause.spec.ts
- packages/core/test/data-query/builder/where-clause.spec.ts
- packages/core/test/template-engine/built-in-extensions/query-builder/execute.spec.ts
- packages/core/test/template-engine/templateEngine.spec.ts
- packages/integration-testing/src/mockExtensions/mockDb.ts
- packages/serve/src/lib/route/route-component/baseRoute.ts
- packages/serve/src/lib/route/route-component/graphQLRoute.ts
- packages/serve/src/lib/route/route-component/restfulRoute.ts
- packages/serve/src/lib/route/routeGenerator.ts
- packages/serve/test/app.spec.ts
- packages/serve/test/route/routeGenerator.spec.ts
- packages/serve/test/server.spec.ts
Support preventing sql injection attack. 
For the detailed description and introduction, please read [Notion link](https://www.notion.so/canner/SQL-Injection-Prevention-3f6789a8eafe48b68b67362ef7e41844) !
🔔 **Notice**: The PR is only to simulates the getting data source and re-parsing parameters flow and add re-parse method in the interface, the really logistic should wait data source to implement,  then could be able to replace it.
For the test result, please see the below test cases that passed the unit test:
-  90b3942 - feat(core, serve): add sql injection prevention structure and flow.
- add prepare parameters method in data source interface.
- inject data source in route generator
- refactor template engine for re-wrap data to context object.
- update req tag runner to get bind …
> Feature: SQL Injection Prevention (Flow Simulation)

- .circleci/config.yml
- .eslintrc.json
- packages/build/src/lib/schema-parser/schemaParser.ts
- packages/core/src/containers/modules/templateEngine.ts
- packages/core/src/lib/artifact-builder/persistent-stores/localFilePersistentStore.ts
- packages/core/src/lib/data-query/builder/dataQueryBuilder.ts
- packages/core/src/lib/data-source/pg.ts
- packages/core/src/lib/template-engine/nunjucksCompiler.ts
- packages/core/src/lib/utils/module.ts
- packages/serve/src/lib/route/route-component/graphQLRoute.ts
- packages/serve/test/app.spec.ts
- packages/serve/test/middlewares/built-in-middlewares/corsMiddleware.spec.ts
- packages/serve/test/middlewares/built-in-middlewares/rateLimitMiddleware.spec.ts
- packages/serve/test/middlewares/built-in-middlewares/response-format/helpers.spec.ts
- packages/serve/test/middlewares/test-custom-middlewares/testModeMiddleware.ts
- packages/serve/test/server.spec.ts
Add Circle CI config.
- Add workflows for Linter and Unit test.
- Fix some lint issues.
- Disable some rules:
- @typescript-eslint/no-non-null-assertion
- @typescript-eslint/no-explicit-any
- set allowCircularSelfDependency to ture
- Add codecov https://app.codecov.io/gh/Canner/vulcan
> Chore: Add Circle CI

- .circleci/config.yml
We used the wrong `--base` argument when running tests on `develop` and `main` branches, this PR set the correct base for them:
- In develop branch: diff with `main` branch.
- In main branch: run all tests.
> FIX: Fix CI script on develop and main branches

- .circleci/config.yml
Circle CI doesn't pull main branch to local, we need to refer to remote branch instead.
> Fix: Change base to remote ref when running test on develop branch

- .circleci/config.yml
- codecov.yml
- packages/core/test/utils/normalizedStringValue.spec.ts
We only run affected packages with CI, so we won't get coverage reports for all packages. But with codecov [merge reports](https://docs.codecov.com/docs/merging-reports) feature, it'll wait for us to send all of reports.
Use flags and enable carryforward option, we can use previous reports when some packages are not changed.
https://about.codecov.io/blog/new-product-test-only-what-you-change-with-carryforward-flags/
Flags: https://docs.codecov.com/docs/flags#tracking-flag-coverage-over-time
Carryforward: https://docs.codecov.com/docs/carryforward-flags
> Chore: Upload report with flags

- tools/scripts/publish.mjs
NX sends string "undefined" when flag is not provided.
> Fix: Fix default tag name of npm

- README.md
- labs/playground1/README.md
- packages/build/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/extension-dbt/package.json
- packages/serve/package.json
- packages/test-utility/package.json
> Chore: Rename repository from vulcan to vulcan-sql

- labs/playground1/sqls/artist/works.sql
- packages/build/test/schema-parser/middleware/responseSampler.spec.ts
- packages/core/src/lib/data-query/builder/dataQueryBuilder.ts
- packages/core/src/lib/data-source/pg.ts
- packages/core/src/lib/template-engine/built-in-extensions/query-builder/executorBuilder.ts
- packages/core/src/lib/template-engine/built-in-extensions/query-builder/executorRunner.ts
- packages/core/src/lib/template-engine/built-in-extensions/query-builder/reqTagBuilder.ts
- packages/core/src/lib/template-engine/nunjucksCompiler.ts
- packages/core/src/lib/utils/index.ts
- packages/core/src/lib/utils/streams.ts
- packages/core/src/models/extensions/dataSource.ts
- packages/core/test/template-engine/built-in-extensions/query-builder/builder.spec.ts
- packages/core/test/template-engine/built-in-extensions/query-builder/execute.spec.ts
- packages/core/test/template-engine/built-in-extensions/query-builder/parameterize.spec.ts
DataSources returned streams instead of arrays, but we haven't adjusted the template output:
```sql
{% req user %}
select * from users where id = {{ context.params.id }}
{% endreq %}
{{ user.value()[0].name }} --- this will be undefined
```
This PR consume the stream and download data for templates.
> Fix: Fix response streams in template

- packages/integration-testing/src/example1/buildAndServe.spec.ts
- packages/serve/src/lib/middleware/response-format/helpers.ts
- packages/serve/src/lib/middleware/response-format/middleware.ts
- packages/serve/src/lib/response-formatter/jsonFormatter.ts
- packages/serve/test/middlewares/built-in-middlewares/response-format/formatResponseMiddleware.spec.ts
- packages/serve/test/middlewares/built-in-middlewares/response-format/helpers.spec.ts
- packages/serve/test/response-formatter/csv.spec.ts
- packages/serve/test/response-formatter/json.spec.ts
- Fix the missing start square bracket `[` for request no existing data and return empty data.
- Fix getting incorrect response format when request indicated.
1.  If the path ending has no format 
- Get default when `Accept` header is also not matched or `Accept` header is not in request (shows by `*/*`)
- If accept format existed, use `Accept` first matched format by support format order
2. If the path ending has format but is not matched
- Throw an error not matter `Accept` match or not ( Because user indicated the format in the end of URL )
4. If the path ending has the format and match, no matter `Accept` is matched or not, use the path ending format
closes #45 and #46
* 01d0a9d - fix(serve): missing start square bracket when data is empty
- Fix to add `[` when no data in `_final` …
> Fix: Missing start square bracket for empty data and get incorrect response format when request indicated

- .circleci/config.yml
- packages/build/package.json
- packages/build/project.json
- packages/cli/Dockerfile
- packages/cli/package.json
- packages/cli/project.json
- packages/cli/src/cli.ts
- packages/cli/src/commands/serve.ts
- packages/cli/src/schemas/init/vulcan.yaml
- packages/cli/test/cli.spec.ts
- packages/cli/test/init.spec.ts
- packages/core/package.json
- packages/core/project.json
- packages/extension-dbt/package.json
- packages/extension-dbt/project.json
- packages/extension-debug-tools/package.json
- packages/extension-debug-tools/project.json
- packages/serve/package.json
- packages/serve/project.json
- packages/test-utility/package.json
- packages/test-utility/project.json
- tools/scripts/publish.mjs
- tools/scripts/version.mjs
Closes #53 
I've set a trigger for nightly build at 23:00 CST
We can also trigger builds via API with parameter `workflow_name` = `nightly build`
~~This PR is done, but waiting for the credentials updated. cc @wwwy3y3~~ (Done)
> Chore: CI for nightly build

- packages/serve/src/lib/middleware/auth/authSourceNormalizerMiddleware.ts
We called the next() function twice while catching errors.
```
2022-09-22 06:21:11.094  DEBUG [SERVE] normalize auth payload source failed, reason => Url ending format not matched in "formats" options
Error: next() called multiple times
at dispatch (/home/goofy/projects/vulcan/node_modules/koa-compose/index.js:36:45)
at AuthSourceNormalizerMiddleware.<anonymous> (/home/goofy/projects/vulcan/labs/playground1/node_modules/@vulcan-sql/serve/src/lib/middleware/auth/authSourceNormalizerMiddleware.js:64:24)
at Generator.throw (<anonymous>)
at rejected (/home/goofy/projects/vulcan/node_modules/tslib/tslib.js:116:69)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
N/A quick fix
Related to #47
> Fix: Fix auth source middleware error handle issue

- package.json
- packages/serve/package.json
The package.json of serve package missed two packages:
- redoc: because we imported it at run time only. I won't import it because we only use the bundle result, but not the source.
- bcryptjs: because we set it to dev dependencies
This PR fix these issues.
N/A quick fix
Related to #38 #26
> Fix: Fix dependencies issues

- package.json
- packages/cli/src/cli.ts
- packages/cli/src/commands/build.ts
- packages/cli/src/commands/serve.ts
- packages/cli/src/commands/start.ts
- packages/cli/src/utils/shutdown.ts
- packages/cli/test/cli.spec.ts
- yarn.lock
Provide a flag --watch, -w for start command, which lets the server watch SQL and schemas changes, and restart the server when needed.
closes #60 
- Watch flag doesn't work in docker CLI, we might need another solution (e.g. polling) for it.
> Feature: Implement start --watch

- packages/cli/src/commands/init.ts
- packages/cli/src/schemas/init/profiles.yaml
- packages/cli/src/schemas/init/sqls/user.sql
- packages/cli/src/schemas/init/sqls/user.yaml
- packages/cli/src/schemas/init/vulcan.yaml
Update these SQL files, schemas, and config.
- move build package to dev dependencies
- update sample queries
- add empty profiles.yaml
closes #83
> Fix: Update CLI initialized files to align the new design

- packages/serve/src/lib/middleware/response-format/middleware.ts
- packages/serve/test/middlewares/built-in-middlewares/response-format/formatResponseMiddleware.spec.ts
Format middleware now only handles Vulcan APIs.
closes #84
- Hardcoding API in middleware is a temporary solution, we should use a configurable path instead.
> Fix: Fix format error when url is not found

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/pull_request_template.md
- Create a PR template.
- Create issue: feature request template.
- Create issue: bug report template
closes #64
> Chore: Add pr and issues templates

- packages/build/package.json
- packages/build/project.json
- packages/cli/package.json
- packages/core/package.json
- packages/extension-dbt/package.json
- packages/extension-debug-tools/package.json
- packages/extension-driver-duckdb/package.json
- packages/extension-driver-pg/package.json
- packages/serve/package.json
- packages/test-utility/package.json
NX detects dependencies from our template js file, so we need to remove it manually.
https://github.com/Canner/vulcan-sql/blob/923605a390b71c81e7871040778362081728c0fa/packages/build/src/models/extensions/packager/assets/entry.js#L1
N/A
> Fix: Remove serve package from dependencies list

- packages/cli/src/commands/init.ts
- packages/serve/src/lib/middleware/response-format/helpers.ts
- packages/serve/test/middlewares/built-in-middlewares/response-format/helpers.spec.ts
- Check the array type when not set `format` field of `response-formats` options and URL does not specify format in the end.
- Update the CLI `vulcan init .` finished message
closes #93
> fix(serve, cli): fix the checking "format" field logistic in "response-formats" options

- packages/doc/docs/api-building/sql-syntax.mdx
- packages/serve/test/middlewares/built-in-middlewares/response-format/helpers.spec.ts
Fix the test cases that fail when running the `checkUsableFormat` function in `helper.spect.ts` from PR #95.
> fix(serve): the test cases of checking useable format  fail.

- packages/extension-driver-pg/src/lib/pgDataSource.ts
- packages/serve/src/lib/server.ts
- Catch all unexpected errors and keep the server still  listening
- using `process.on('uncaughtException', (err) => {....})` to catch, including event emitter errors.
- Ignore and warn the connection failed message when executing query in pg driver
closes #102
> Fix: Catch all errors to prevent server crashes

- .circleci/config.yml
Circle [Docker Layer Caching (DLC)](https://circleci.com/docs/docker-layer-caching/) used 30,000 credits this month, but it only benefits nightly build jobs, so we can disable it to save some credits.
N/A
> Chore: Disable circleci DLC

- package.json
- packages/cli/test/init.spec.ts
- packages/core/src/lib/artifact-builder/vulcanArtifactBuilder.ts
- packages/core/src/lib/validators/constraints.ts
- packages/core/src/models/artifact.ts
- packages/core/test/validators/constraint-serialize.spec.ts
- yarn.lock
The catalog server needs the constraints of each request parameter, but we haven't serialized all of them.
This PR used `class-transformer` to transform classes into plain objects before saving artifacts and to transform plain objects into classes while reading them.
closes #105
We'd need to rebuild to get constraints from artifacts.
Here are some simple codes the get constraints. cc @wwwy3y3 
```ts
import * as jsYAML from 'js-yaml';
import { promises as fs } from 'fs';
import * as path from 'path';
import {
APISchema,
ArtifactBuilder,
BuiltInArtifactKeys,
Container,
EnumConstraint,
TYPES,
} from '@vulcan-sql/core';
const container = new Container();
// Read config
const configPath = path.resolve(process.cwd(), 'vulcan.yaml');
const config: any = jsYAML.load(await fs.readFile(configPath, …
```
> Feature: Serialize/Deserialize all artifacts

- package.json
- packages/extension-driver-duckdb/src/lib/duckdbDataSource.ts
- packages/extension-driver-pg/src/lib/pgDataSource.ts
- packages/extension-driver-pg/test/errorHandler.spec.ts
- packages/extension-driver-pg/test/pgDataSource.spec.ts
- packages/extension-driver-pg/test/pgServer.ts
- yarn.lock
PG
- Remove the duplicated event register because it adds listeners for each request but never removes them.
- Fix duplicated connection pools issue.
- Add test cases for error handlers.
DuckDB
- upgrade to 0.5.1
closes #106
> Fix: Improve the stabilities of PostgreSQL and DuckDB drivers

- .gitignore
- packages/core/src/lib/data-query/parameterizer.ts
- packages/core/src/lib/template-engine/built-in-extensions/query-builder/constants.ts
- packages/core/src/lib/template-engine/built-in-extensions/query-builder/index.ts
- packages/core/src/lib/template-engine/built-in-extensions/query-builder/voidFIlterRunner.ts
- packages/core/src/lib/template-engine/built-in-extensions/query-builder/voidFilterBuilder.ts
- packages/core/test/template-engine/built-in-extensions/query-builder/parameterize.spec.ts
- packages/doc/docs/api-building/sql-syntax.mdx
1. Ignore parameterization of undefined value.
```sql
{{ context.params.somethingUndefined }} -- output nothing 
```
2. Add `void` filter
```sql
{% set someArr = [] %}
{{ someArr.push(1) |  void }}
select {{ someArr[0] }} as a;
```
Document
https://vulcan-sql-document-git-fix-avoid-pa-8e149a-vulcan-sql-document.vercel.app/docs/api-building/sql-syntax#void-filter
closes #112
> Fix: Improper parameterizing of variables without values

- README.md
- package.json
- packages/doc/docs/connectors.mdx
- packages/doc/docs/connectors/bigquery.mdx
- packages/extension-driver-bq/.eslintrc.json
- packages/extension-driver-bq/README.md
- packages/extension-driver-bq/jest.config.ts
- packages/extension-driver-bq/package.json
- packages/extension-driver-bq/project.json
- packages/extension-driver-bq/src/index.ts
- packages/extension-driver-bq/src/lib/bqDataSource.ts
- packages/extension-driver-bq/src/lib/bqlSqlBuilder.ts
- packages/extension-driver-bq/src/lib/typeMapper.ts
- packages/extension-driver-bq/test/bqDataSource.spec.ts
- packages/extension-driver-bq/test/bqServer.ts
- packages/extension-driver-bq/test/bqlSqlBuilder.spec.ts
- packages/extension-driver-bq/tsconfig.json
- packages/extension-driver-bq/tsconfig.lib.json
- packages/extension-driver-bq/tsconfig.spec.json
- tsconfig.base.json
- workspace.json
- yarn.lock
Add bigquery data source and update the document.
Document: 
https://vulcan-sql-document-git-feature-ds-bigquery-vulcan-sql-document.vercel.app/docs/connectors/bigquery
closes #57 
The official SDK prints logs with console and files, which should be avoided. #126
> Feature: BigQuery support - statement

- packages/core/src/lib/template-engine/built-in-extensions/index.ts
- packages/core/src/lib/template-engine/built-in-extensions/masking/index.ts
- packages/core/src/lib/template-engine/built-in-extensions/masking/maskingTagBuilder.ts
- packages/core/src/lib/template-engine/built-in-extensions/masking/maskingTagRunner.ts
- packages/core/test/template-engine/built-in-extensions/masking/masking.spec.ts
- packages/doc/docs/api-building/sql-syntax.mdx
- packages/extension-driver-snowflake/test/snowflakeDataSource.spec.ts
I made the masking tag, and support the partial masking function.
The built-in tag `masking` is added using the following syntax:
```
{% masking <column-name> <masking-function> %}
```
For an example of SQL
```sql
SELECT
{% masking id partial(2, 'xxxxxxx', 0) %} as id,
name
FROM user;
```
```sql
SELECT
{% masking id partial(2, 'xxxxxxx', 2) %} as id,
name
FROM user;
```
closes #139
- Implementing the partial function is based on considering the currently supported connectors and using a generic function to implement it.
- Per discussion with Ivan before, maybe... in order to cope with different connectors, it may be possible in the future that implement a masking function for each connector
> Feature: Dynamic data masking - custom string

- packages/build/src/lib/schema-parser/schema-reader/fileSchemaReader.ts
- packages/build/test/document-generator/spec-generator/schema.ts
- packages/core/src/lib/template-engine/template-providers/fileTemplateProvider.ts
Fix the path of sql files not being recognized correctly in winOS
#143 
Windows use backslash when using path.resolve, e.g. `C:\\Users\\xxxxx\\cli`, but `glob` accepts only forward ward slash, so we make the windows path to linux path to make `glob` accepted
Glob: https://github.com/isaacs/node-glob#windows
Path separator: https://nodejs.org/api/path.html#pathsep
> Fix: Fix the path of sql files not being recognized correctly in winOS

- packages/build/src/lib/schema-parser/middleware/responseSampler.ts
- packages/core/src/lib/template-engine/compiler.ts
- packages/core/src/lib/template-engine/nunjucksExecutionMetadata.ts
- packages/core/src/models/artifact.ts
- packages/doc/docs/api-building/sql-syntax.mdx
- packages/serve/src/lib/route/route-component/baseRoute.ts
- packages/serve/src/lib/route/route-component/graphQLRoute.ts
- packages/serve/src/lib/route/route-component/restfulRoute.ts
The route information like host, path ...etc. are useful while rendering SQL queries.
```sql
select
*
from
"artists"
where
{{ context.req.method }} = "GET"
and
{{ context.header.customParameters }} = "custom parameters"
......
```
closes #62
> Feature: Passing route information to template engine

- packages/core/src/models/profile.ts
- packages/core/test/data-query/profile/profile-readers/localFile.spec.ts
- packages/core/test/data-query/profile/profile-readers/profile1.yaml
- packages/extension-driver-bq/README.md
- packages/extension-driver-bq/src/lib/bqDataSource.ts
- packages/extension-driver-bq/test/bqDataSource.spec.ts
- packages/extension-driver-bq/test/bqServer.ts
- yarn.lock
What this PR do:
- extend Profile interface to specify bucket
- modify test case due to extend the Profile interface
- implement export method in bqDataSource
- add test cases to test export method
The export flow:
- Use [EXPORT DATA](https://cloud.google.com/bigquery/docs/reference/standard-sql/other-statements#export_data_statement) statement exporting data to GCS as parquet format.
- Download the parquet file after exporting.
- Remove the parquet file from GCS
issue #155 
- The export method support exporting the large file(over 1GB) and will be cut into multiple files automatically
- The [data type](https://cloud.google.com/bigquery/docs/exporting-data?hl=en#parquet_export_details) is automatically converted when exporting to parquet format by BigQuery during exporting
SQL: `SELECT …
> Feature: Cache feature support BigQuery datasource #155

- package.json
- yarn.lock
Add @google-cloud/storage dependency
Without it, building bq extension will encounter following issues
```
> nx run extension-driver-bq:tsc
Compiling TypeScript files for project "extension-driver-bq"...
packages/extension-driver-bq/src/lib/bqDataSource.ts:16:41 - error TS2307: Cannot find module '@google-cloud/storage' or its corresponding type declarations.
16 import { Storage, StorageOptions } from '@google-cloud/storage';
~~~~~~~~~~~~~~~~~~~~~~~
packages/extension-driver-bq/src/lib/bqDataSource.ts:97:40 - error TS7006: Parameter 'file' implicitly has an 'any' type.
97         getFilesResponse[0].map(async (file) => {
```
> Add @google-cloud/storage dependency

- packages/extension-driver-snowflake/src/index.ts
Using require seems to cause module not found issue. Setting env instead.
[CI failed link](https://app.circleci.com/pipelines/github/Canner/vulcan-sql/920/workflows/9613aabf-8595-46da-a93d-01cbc6e2ab50/jobs/2799)
> Change the way to suppress the aws-sdk warning

- packages/doc/docs/get-started/first-api.mdx
In this [page](https://vulcansql.com/docs/get-started/first-api), the api endpoint should be `http://localhost:3000/api/flights` instead of `http://localhost:3000/api/user`
None
None
> fix(doc): wrong api endpoint

- packages/extension-driver-canner/.eslintrc.json
- packages/extension-driver-canner/README.md
- packages/extension-driver-canner/jest.config.ts
- packages/extension-driver-canner/package.json
- packages/extension-driver-canner/project.json
- packages/extension-driver-canner/src/index.ts
- packages/extension-driver-canner/src/lib/cannerAdapter.ts
- packages/extension-driver-canner/src/lib/cannerDataSource.ts
- packages/extension-driver-canner/src/lib/config.ts
- packages/extension-driver-canner/src/lib/sqlBuilder.ts
- packages/extension-driver-canner/src/lib/typeMapper.ts
- packages/extension-driver-canner/test/cannerAdapter.spec.ts
- packages/extension-driver-canner/test/cannerDataSource.spec.ts
- packages/extension-driver-canner/test/cannerServer.ts
- packages/extension-driver-canner/test/sqlBuilder.spec.ts
- packages/extension-driver-canner/tsconfig.json
- packages/extension-driver-canner/tsconfig.lib.json
- packages/extension-driver-canner/tsconfig.spec.json
- tsconfig.base.json
- workspace.json
What this PR does:
- Support Canner Enterprise as a data source in VulcanSQL
- Caching feature in VulcanSQL is also supported 
We use PostgreSQL Wire Protocol to connect to canner enterprise and execute the sql in VulcanSQL.
Check the [doc](https://docs.cannerdata.com/product/api_sdk/pg/pg_overview) for more connecting info 
The export flow:
- Use Canner Enterprise API to create an async-query that will execute the sql statement and turn the query result into parquet files and stored in S3 
- wait the async-query to finished
- Get the presigned URLs of this async-query and download.
For the canner API info, please check [here](https://documenter.getpostman.com/view/21257531/2s93CGSc5k#8e91682d-5d3a-4f70-a2f5-9e90039a9c39)
issue #169 
- The Canner async-query APIs have stored the query …
> Feature: Canner enterprise connector 

- packages/extension-store-canner/src/lib/canner/persistenceStore.ts
- packages/extension-store-canner/src/lib/canner/profileReader.ts
- packages/extension-store-canner/src/test/cannerPersistenceStore.spec.ts
- packages/extension-store-canner/src/test/cannerProfileReader.spec.ts
- packages/serve/src/lib/evaluator/evaluator.ts
Faced the issues when testing the VulcanSQL Integration with Canner Enterprise:
1. API Documentation is not consistent for the API prefix when getting the artifacts from Canner Enterprise and merging to one artifact, we need to make the `operationId` and `summary` field add the workspace SQL name in `specs`, then it could solve the solution.
2. The generated canner profile name in `CannerProfileReader` is not the same as `CannerPersistenceStore`, so we need to fix it to the same `canner-{workspaceSqlName}`.
closes N/A
We opened a Canner Enterprise of PR testing env and create two workspaces `w1` and `w2` with the tables:
Use the In the VulcanSQL `labs` and create two profiles `canner-w1` and `canner-w2` with temporal PAT fo connecting Canner Enterprise by `extension-driver-canner` through …
> Fix: Face issue when testing the VulcanSQL integration with Canner Enteprise

- packages/extension-authenticator-canner/project.json
Discover "project.json" missed "publish" command in "extension-authenticator-canner", so when do the publish to NPM, it not existed, and also discover other commands do not use `replaceAlias.ts` file, so we need to add it.
N/A
> Fix: update "project.json" to sync and missed publish command for "extension-authenticator-canner"

- packages/extension-authenticator-canner/README.md
In the `extension-canner-authenticator` package, exist the typo for `port` options, it may need to fix, because the README also displays on [NPM package](https://www.npmjs.com/package/@vulcan-sql/extension-authenticator-canner).
N/A
N/A
> Fix: Typo issue for "port" in the README at "extension-canner-authenticator".

- packages/extension-authenticator-canner/src/lib/authenticator/pat.ts
- packages/extension-authenticator-canner/src/test/cannerPATAuthenticator.spec.ts
- packages/serve/src/lib/auth/httpBasicAuthenticator.ts
- packages/serve/src/lib/auth/passwordFileAuthenticator.ts
- packages/serve/src/lib/auth/simpleTokenAuthenticator.ts
- packages/serve/src/lib/middleware/auth/authCredentialsMiddleware.ts
- packages/serve/test/auth/basicAuthenticator.spec.ts
- packages/serve/test/auth/passwordFileAuthenticator.spec.ts
- packages/serve/test/auth/simpleTokenAuthenticator.spec.ts
- packages/serve/test/middlewares/built-in-middlewares/authCredentialMiddleware.spec.ts
Refactor the authentication middleware to match the authenticator first then validate the user with the matched authenticator 
We still having "INDETERMINATE" state in the build-in authenticators and check the authenticator is set proper, because build-in authenticators will always be initialized and the scenario is user send a request with the token identifier which is the authenticator that did not been configured in the vulcan.yaml file
> Chore(Auth Middleware): match authenticator in middleware

- packages/build/src/models/extensions/packager/packager.ts
- packages/cli/src/commands/catalog.ts
1. In the `vulcan package` command line process,  add conditional `package.json` retrieving when the user is in binary mode. (#222)
2. Adjust the `vulcan catalog` version since it can read the `package.json` inside the binary.
3. Add an exception for catalog packager if the user not installed `@vulcan-sql/catalog-server`.
closes #222
> Fix: `vulcan package` throws exception using VulcanSQL cli in binary version

- packages/doc/docs/get-started/installation.mdx
change binary download links to ones on GitHub release in order to track binary VulcanSQL download number
None
None
> chore: change binary download links

- packages/extension-driver-duckdb/README.md
- packages/extension-driver-duckdb/src/lib/duckdbDataSource.ts
- packages/extension-driver-duckdb/src/lib/duckdbExtensionLoader.ts
- packages/extension-driver-duckdb/tests/configurationLoader.spec.ts
- packages/extension-driver-duckdb/tests/duckdbDataSource.spec.ts
This PR uses "[httpfs](https://duckdb.org/docs/extensions/httpfs)" extension and  allows DuckDB to read remote data.
The remote files which were partitioned using "Hive Partition" is also supported. Read the [doc](https://duckdb.org/docs/data/partitioning/hive_partitioning#hive-partitioning) for more.
#231 
The configuration parameters set in the profile.yaml file were used as the default credential when sending request to DuckDB,  To read data using a different credential, utilize the [Per-Request Configuration](https://duckdb.org/docs/extensions/httpfs#per-request-configuration) and concat the credential after your object url
Example: 
```
SELECT *
FROM 's3://bucket/file.parquet?s3_region=region&s3_session_token=session_token' T1
INNER JOIN …
```
> feature: support reading data from data lake

- packages/doc/docs/get-started/installation.mdx
In the current Release process, we will compress the constructed binary files and put them into the assets in the release notes. The file format is `vulcan.{os}.{version}.{tar.gz/zip}`.
We should simplify. As we know, each Release Note not only has the assets part but also has the Release version number, so we will change the file name to no longer contain the version number part.
So, we will have the following changes:
1. Change the file name format.
- Ubuntu: **vulcan.linux.tar.gz**
- Mac OS: **vulcan.osx.tar.gz**
- Windows: **vulcan.win.zip**
2. It is no longer necessary to change the download link in the docs
closes #xx
Reference doc: https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases#linking-to-the-latest-release
> Chore: update release assets info of the binary process

- labs/playground1/Makefile
- packages/doc/docs/extensions/huggingface-table-question-answering.mdx
- packages/extension-huggingface/README.md
- packages/extension-huggingface/src/lib/filters/tableQuestionAnswering.ts
- packages/extension-huggingface/test/tableQuestionAnswering.spec.ts
The HuggingFace library or API will respond to different results with an aggregator field ( e.g: `COUNT`, 'AVERAGE', 'NONE'....) according to the different models adopted, so we decide to dump the result object to JSON string and delegate user to decompose it and use the result according to different scenarios.
Below is a sample of the response to the HuggingFace table question answering:
```sql
{% set data = [
{
"repository": "vulcan-sql",
"topic": ["analytics", "data-lake", "data-warehouse", "api-builder"],
"description":"Create and share Data APIs fast! Data API framework for DuckDB, ClickHouse, Snowflake, BigQuery, PostgreSQL"
},
{
"repository": "accio",
"topic": ["data-analytics", "data-lake", "data-warehouse", "bussiness-intelligence"],
"description": "Query Your Data Warehouse Like …
```
> Fix: change the output format to JSON string of hugging face extension

- labs/playground1/Makefile
- labs/playground1/README.md
- packages/extension-driver-canner/src/lib/cannerDataSource.ts
When using  `exetnsion-driver-canner` and caching dataset feature, the parquet file was downloaded from Canner Enterprise, but not find it in the local folder and cause vulcan-sql to fail.
The reason is that the downloaded parquet file does not include `parquet` extension name, so it caused the cache layer could not to find the parquet file and failed. After renaming the filename when downloading, the issue has been fixed, see:
closes #xx
> Fix: Rename the downloaded parquet file to add parquet extension

- packages/doc/docs/extensions/dbt.mdx
- packages/doc/docs/extensions/huggingface/huggingface-table-question-answering.mdx
Add examples links in documents of dbt and hugging face extensions
none
> feature: add example links

- packages/doc/docs/develop/cache.mdx
add supported caching data sources description text
None
> feature: add supported caching data sources description text

- packages/doc/docs/connect/ksqldb.mdx
- packages/doc/sidebars.js
- packages/extension-driver-ksqldb/.eslintrc.json
- packages/extension-driver-ksqldb/README.md
- packages/extension-driver-ksqldb/jest.config.ts
- packages/extension-driver-ksqldb/package.json
- packages/extension-driver-ksqldb/project.json
- packages/extension-driver-ksqldb/src/index.ts
- packages/extension-driver-ksqldb/src/lib/extension-driver-ksqldb.spec.ts
- packages/extension-driver-ksqldb/src/lib/extension-driver-ksqldb.ts
- packages/extension-driver-ksqldb/src/lib/ksqldbDataSource.ts
- packages/extension-driver-ksqldb/src/lib/restfulClient.ts
- packages/extension-driver-ksqldb/src/lib/sqlBuilder.ts
- packages/extension-driver-ksqldb/src/lib/typeMapper.ts
- packages/extension-driver-ksqldb/test/docker/compose.ts
- packages/extension-driver-ksqldb/test/docker/docker-compose.yml
- packages/extension-driver-ksqldb/test/docker/jaas_config.file
- packages/extension-driver-ksqldb/test/docker/password-file
- packages/extension-driver-ksqldb/test/ksqlDbDataSource.spec.ts
- packages/extension-driver-ksqldb/test/ksqlDbServer.ts
- packages/extension-driver-ksqldb/test/sqlBuilder.spec.ts
- packages/extension-driver-ksqldb/tsconfig.json
- packages/extension-driver-ksqldb/tsconfig.lib.json
- packages/extension-driver-ksqldb/tsconfig.spec.json
- tsconfig.base.json
- types/dockerode-compose.d.ts
- workspace.json
Support KSqlDb driver to connect KSqldb data source
closes N/A
Follow the official site quick start step below:
https://ksqldb.io/quickstart.html
or run the cmd line in the root directory:
- start the docker containers in [`docker-compose.yml`](https://github.com/Canner/vulcan-sql/blob/feature/ksqldb-driver/packages/extension-driver-ksqldb/test/docker/docker-compose.yml)
```bash
docker-compose -f ./packages/extension-driver-ksqldb/test/docker/docker-compose.yml up -d
```
- open db terminal
```bash
docker exec -it ksqldb-cli ksql http://ksqldb-server:8088
```
- create & insert reference data
```bash
CREATE STREAM riderLocations (profileId VARCHAR, latitude DOUBLE, longitude DOUBLE)
WITH (kafka_topic='locations', value_format='json', partitions=1);
CREATE TABLE currentLocation AS
SELECT …
```
> Feature: Support KSqlDb driver

- packages/doc/docs/data-privacy/authn.mdx
- packages/doc/docs/data-privacy/authz.mdx
update authentication and authorization docs
None
> update authentication and authorization docs

- packages/build/src/lib/schema-parser/schemaParser.ts
- packages/catalog-server/utils/vulcanSQLAdapter.ts
- packages/serve/src/lib/catalog-router/catalogRouters.ts
- packages/serve/src/lib/route/route-component/restfulRoute.ts
- packages/serve/test/app.spec.ts
Fix wrong api URL path on Open API doc. Since the url path of API generated by VulcanSQL will start from '/api', but there's no `/api` prefix shown on Open API doc.
None
> fix wrong api urls on openapi doc

- packages/build/src/lib/schema-parser/schemaParser.ts
- packages/catalog-server/utils/vulcanSQLAdapter.ts
- packages/extension-store-canner/src/lib/canner/persistenceStore.ts
- packages/extension-store-canner/src/test/cannerPersistenceStore.spec.ts
- packages/serve/src/lib/catalog-router/catalogRouters.ts
- packages/serve/src/lib/route/route-component/restfulRoute.ts
- packages/serve/test/app.spec.ts
For the Canner Enterprise product, the extension-store-canner pulls the result.json from Minio to merge into one file, it lacks the profile setting of the cache layer in the schema, so we need to fix it and let caching datasets functionality works.
closes #275
Opened a Canner Enterprise of PR testing env and create the `w1` workspaces with the table:
Use the In the VulcanSQL labs and create canner-w1 profiles with temporal PAT for connecting Canner Enterprise by extension-driver-canner through PG Wire Protocol:
Enable caching for vulcan.yaml
```yaml
cache:
type: parquet
folderPath: tmp
loader: duckdb
```
Apply my bugfix code for `package.json` of labs
```
{
"name": "...",
"dependencies": {
...
"@vulcan-sql/extension-store-canner": "../../dist/packages/extension-store-canner",
},
...
}
``` …
> Fix: Correct the profile of cache layer schema for Canner Persistence Store

- packages/core/src/lib/utils/analyzer.ts
- packages/core/src/lib/utils/index.ts
- packages/core/test/analyzer.spec.ts
- packages/extension-driver-duckdb/README.md
- packages/extension-driver-duckdb/src/lib/duckdbDataSource.ts
- packages/extension-driver-duckdb/src/lib/sqlBuilder.ts
- packages/extension-driver-duckdb/tests/duckdbDataSource.spec.ts
- packages/extension-driver-duckdb/tests/sqlBuilder.spec.ts
- packages/serve/src/lib/server.ts
- types/duckdb.d.ts
- Add performance analysis tool
- Modify Duckdb data source execute method: 
- Pararelize execution and use connection.all  instead of nextChunk
Note: 
With the same data, the performance of stream.nextChunk is 1.5~2 times of the performance of connection.all
> Feature: improve duckdbDataSource performance

- packages/core/src/containers/modules/dataSource.ts
- packages/core/src/lib/cache-layer/cacheLayerLoader.ts
- packages/core/src/models/artifact.ts
- packages/core/src/models/cacheLayerOptions.ts
- packages/core/test/cache-layer/cacheLayerLoader.spec.ts
- packages/core/test/containers/cacheLayer.spec.ts
- Make caching layer datasource can be persistent 
- It's will reduce the memory usage when loading parquet file to cache 
- Skip exporting data if parquet file exists when loading cache
- avoid exporting/downloading data if the parquet files in path is still fresh
> Fix: caching layer persistent

- packages/core/src/lib/cache-layer/cacheLayerLoader.ts
- packages/core/test/cache-layer/cacheLayerLoader.spec.ts
Remove the dormant Parquet files to free up hardware storage as these files are no longer required.
Using playground to test, under the tmp/artist-artist/canner/lineitem folder, the elder parquet files were evict after exporting data successfully.
> Fix: Evict unused parquet file after exporting cache data

- packages/catalog-server/lib/api.ts
- packages/catalog-server/lib/apollo.ts
- packages/catalog-server/next.config.js
- Add `BASE_URL` env for catalog server hosting when needed
This adjustment is aligned with https://catalog-server.vercel.app
closes N/A
> Feature: Provide BASE_URL for Catalog Server Hosting

- packages/core/src/lib/data-query/builder/dataQueryBuilder.ts
- packages/core/src/lib/data-query/executor.ts
- packages/core/src/lib/template-engine/built-in-extensions/cache/cacheTagRunner.ts
- packages/core/src/lib/template-engine/built-in-extensions/query-builder/reqTagRunner.ts
- packages/core/src/lib/template-engine/compiler.ts
- packages/core/src/lib/template-engine/nunjucksExecutionMetadata.ts
- packages/core/src/models/artifact.ts
- packages/core/src/models/extensions/dataSource.ts
- packages/core/test/data-query/builder/group-by-clause.spec.ts
- packages/core/test/data-query/builder/having-clause.spec.ts
- packages/core/test/data-query/builder/join-clause.spec.ts
- packages/core/test/data-query/builder/limit-offset-clause.spec.ts
- packages/core/test/data-query/builder/order-by-clause.spec.ts
- packages/core/test/data-query/builder/parameterize.spec.ts
- packages/core/test/data-query/builder/select-clause.spec.ts
- packages/core/test/data-query/builder/where-clause.spec.ts
- packages/core/test/template-engine/built-in-extensions/query-builder/operations.spec.ts
- packages/extension-driver-canner/src/lib/cannerDataSource.ts
- packages/extension-driver-canner/test/cannerDataSource.spec.ts
- packages/extension-driver-canner/test/mock/index.ts
- packages/extension-driver-canner/test/mock/mockCannerDataSource.ts
- packages/extension-driver-duckdb/src/lib/duckdbDataSource.ts
- packages/serve/src/lib/route/route-component/baseRoute.ts
- packages/serve/src/lib/route/route-component/graphQLRoute.ts
- packages/serve/src/lib/route/route-component/restfulRoute.ts
To use the API request context(e.g.: some customized headers) in dataSource, we need to first inject the API context into NunjucksExecutionMetadata which stores global info and passes around tag runners, and inject API context into dataSource in each tag runner.
Pass API request context in the Nunjucks filter is not supported yet 
unit test ✅ 
manual integration test using canner driver ✅ 
- can use headers to access canner
> Feature(Core, Extension-driver-canner): pass headers down to datasource & use info in API headers to connect to canner

- packages/core/src/containers/modules/extension.ts
- packages/core/src/containers/types.ts
- packages/core/src/index.ts
- packages/core/src/lib/cache-layer/cacheLayerLoader.ts
- packages/core/src/lib/cache-layer/cacheLayerRefresher.ts
- packages/core/src/lib/loggers/httpLogger.ts
- packages/core/src/lib/loggers/index.ts
- packages/core/src/lib/template-engine/compiler-environment/base.ts
- packages/core/src/lib/utils/url.ts
- packages/core/src/models/coreOptions.ts
- packages/core/src/models/extensions/index.ts
- packages/core/src/models/extensions/logger.ts
- packages/core/src/models/index.ts
- packages/core/src/models/loggerOptions.ts
- packages/core/test/cache-layer/cacheLayerRefresher.spec.ts
- packages/core/test/httplogger.spec.ts
- packages/core/test/utils/url.spec.ts
- packages/extension-authenticator-canner/src/lib/authenticator/pat.ts
- packages/serve/src/lib/middleware/activityLogMiddleware.ts
- packages/serve/src/lib/middleware/auth/authCredentialsMiddleware.ts
- packages/serve/src/lib/middleware/auth/authRouterMiddleware.ts
- packages/serve/src/lib/middleware/index.ts
- packages/serve/test/middlewares/built-in-middlewares/activityLogMiddleware.spec.ts
Add a activity log extension to send activity log like incoming request information and cache refreshing result.
Activity logs aim to provide a more specific and accurate information compared to the access log or debug logger stdout. 
```
activity-log:
enabled: true
options:
http-logger:
connection:
ssl: boolean. # use https or not
host: string
port: integer
path: "url path"
```
After you set your project config, vulcan server will send activity log to remote server asynchronously when cache refreshing job is done and after processed an API request.
A cache refreshing activity log will contain info
```
logTime(timestamp in UTC) -- the time that refresh job started
urlPath -- indicate which API it belong
sql -- the sql statement that will be executed 
refreshResult -- Enum(success, …
```
> Feature(CORE): Activity log extension

- packages/core/src/lib/cache-layer/cacheLayerLoader.ts
- packages/core/src/models/artifact.ts
- packages/core/src/models/extensions/dataSource.ts
- packages/core/src/models/profile.ts
- packages/extension-driver-canner/src/lib/cannerAdapter.ts
- packages/extension-driver-canner/src/lib/cannerDataSource.ts
- packages/extension-driver-canner/test/cannerDataSource.spec.ts
- packages/extension-driver-canner/test/cannerServer.ts
- packages/extension-store-canner/README.md
- packages/extension-store-canner/src/lib/canner/profileReader.ts
- packages/extension-store-canner/src/lib/config.ts
- packages/extension-store-canner/src/test/cannerProfileReader.spec.ts
Extends CacheLayerInfo interface and Profile interface to store properties that pass to the data source.
profile.yaml
```
- name: duckdb
type: duckdb
connection:
host: ...
otherConnectionInfo
allow: *
// new added
properties:
some-configuration that can be read in the setting
```
API schema
```
urlPath: /artist/:id
cache:
- cacheTableName: foo
sql: 'select 1'
profile: duckdb
// new added
options:
foo: bar
profile: duckdb
```
> Feature: extends CacheLayerInfo interface and Profile interface

- packages/core/src/lib/template-engine/built-in-extensions/sql-helper/index.ts
- packages/core/src/lib/template-engine/built-in-extensions/sql-helper/typeofBuilder.ts
- packages/core/src/lib/template-engine/built-in-extensions/sql-helper/typeofRunner.ts
This pull request introduces a new filter called `typeof` that allows retrieving the type of a variable in templates. 
For example, you can now use 
`{% if context.params.foo|typeof == 'string' %}` 
to conditionally execute code based on the type of the `foo` variable.
n/a
> feat(core): add typeof filter

- packages/extension-driver-duckdb/src/lib/duckdbDataSource.ts
- packages/extension-driver-duckdb/src/lib/duckdbExtensionLoader.ts
- packages/extension-driver-duckdb/tests/duckdbDataSource.spec.ts
This PR addresses an issue where the connection pool in DuckDB queries might fail due to incorrect initialization. The problem has been resolved, ensuring that the connection pool is properly initialized.
n/a
> Fix DuckDB Connection Pool Initialization Issue

- package.json
- yarn.lock
Updated class-validator because the old version had some security issues:
https://github.com/advisories/GHSA-fj58-h2fr-3pp2
> chore: update class-validator

- packages/extension-api-caller/test/restApiCaller.spec.ts
- packages/extension-driver-duckdb/src/lib/duckdbDataSource.ts
- packages/extension-driver-duckdb/src/lib/sqlBuilder.ts
The APIs with sql start with `WITH RECURSIVE` can not get response from server when the responding row is larger than the chunk size. 
closes #324
> Fix: fix incorrect condition to use restDataStream

- packages/admin-ui/components/form/ExpressionProperties.tsx
- packages/admin-ui/components/modals/AddDimensionFieldModal.tsx
- packages/admin-ui/components/modals/AddMeasureFieldModal.tsx
- packages/admin-ui/components/modals/AddRelationModal.tsx
- packages/admin-ui/components/modals/AddWindowFieldModal.tsx
- packages/admin-ui/components/pages/modeling/MetricDrawer.tsx
- packages/admin-ui/components/pages/modeling/form/MetricBasicForm.tsx
- packages/admin-ui/components/pages/modeling/form/MetricDetailForm.tsx
- packages/admin-ui/components/pages/modeling/form/ModelDetailForm.tsx
- packages/admin-ui/components/pages/modeling/form/PreviewDataContent.tsx
- packages/admin-ui/components/selectors/DescriptiveSelector.tsx
- packages/admin-ui/components/selectors/ExpressionSelector.tsx
- packages/admin-ui/components/selectors/modelFieldSelector/index.tsx
- packages/admin-ui/components/table/SelectionRelationTable.tsx
- packages/admin-ui/components/tableFormControls/CaculatedFieldTableFormControl.tsx
- packages/admin-ui/components/tableFormControls/DimensionTableFormControl.tsx
- packages/admin-ui/components/tableFormControls/MeasureTableFormControl.tsx
- packages/admin-ui/components/tableFormControls/WindowTableFormControl.tsx
- packages/admin-ui/components/tableFormControls/base.tsx
- packages/admin-ui/hooks/useExpressionFieldOptions.tsx
- packages/admin-ui/hooks/useMetricDetailFormOptions.tsx
- packages/admin-ui/hooks/useModelFieldOptions.tsx
- packages/admin-ui/pages/component.tsx
- packages/admin-ui/styles/components/table.less
- packages/admin-ui/utils/enum/modeling.ts
- packages/admin-ui/utils/error/dictionary.ts
- can create & update
- Metrics:
- Name
- From
- Pick a model / metric
- Type: Simple, Cumulative
- Measure (語法跟 calculated field 支援的一致)
- Type = Simple
- Dimension
- pick a field
- 可以不斷透過 relation 連結到下個 model
- if field type = date or timestamp, 提供使用者選擇顆粒度 (granularity) 要 day/month/year
- Type = Cumulative
- Window
- pick a field (僅能選擇 date, timestamp)
- Time Unit (選擇 YEAR, QUARTER, MONTH, WEEK, DAY, HOUR, MINUTE, SECOND)
closes #xx
> Feature: Metric Drawer

- packages/admin-ui/components/modals/AddCaculatedFieldModal.tsx
- packages/admin-ui/components/modals/AddDimensionFieldModal.tsx
- packages/admin-ui/components/modals/AddMeasureFieldModal.tsx
- packages/admin-ui/components/modals/AddRelationModal.tsx
- packages/admin-ui/components/modals/AddWindowFieldModal.tsx
- packages/admin-ui/components/modals/UpdateMetadataModal.tsx
- packages/admin-ui/components/pages/modeling/MetadataDrawer.tsx
- packages/admin-ui/components/pages/modeling/MetricDrawer.tsx
- packages/admin-ui/components/pages/modeling/ModelDrawer.tsx
- packages/admin-ui/components/table/CaculatedFieldTable.tsx
- packages/admin-ui/components/table/DimensionFieldTable.tsx
- packages/admin-ui/components/table/FieldTable.tsx
- packages/admin-ui/components/table/MeasureFieldTable.tsx
- packages/admin-ui/components/table/MetadataBaseTable.tsx
- packages/admin-ui/components/table/RelationTable.tsx
- packages/admin-ui/components/table/WindowFieldTable.tsx
- packages/admin-ui/components/tableFormControls/CaculatedFieldTableFormControl.tsx
- packages/admin-ui/components/tableFormControls/DimensionTableFormControl.tsx
- packages/admin-ui/components/tableFormControls/MeasureTableFormControl.tsx
- packages/admin-ui/components/tableFormControls/RelationTableFormControl.tsx
- packages/admin-ui/components/tableFormControls/WindowTableFormControl.tsx
- packages/admin-ui/components/tableFormControls/base.tsx
- packages/admin-ui/hooks/useDrawerAction.tsx
- packages/admin-ui/hooks/useModalAction.tsx
- packages/admin-ui/pages/component.tsx
- packages/admin-ui/utils/error/dictionary.ts
- View Metadata Drawer
- Update Metadata Popup
- The caculated field will remain update in model drawer which metadata drawer not provide update caculated fields, only can update it’s metadata.
closes #xx
> Feature: Metadata Drawer
